"""Bundled fallback data for Minecraft 1.21.1 worldgen.

Used when the instance's vanilla client jar cannot be found. Every table below was
extracted from the 1.21.1 client jar data files, so ids, tag membership and
structure_set placement values match the game. The scanner merges these under
source "vanilla-bundled" only for entries the jar scan did not provide.
"""
from __future__ import annotations

MC_VERSION = "1.21.1"

# biome id -> climate fields from data/minecraft/worldgen/biome/*.json
BIOMES: dict[str, dict] = {'minecraft:badlands': {'has_precipitation': False, 'temperature': 2.0},
 'minecraft:bamboo_jungle': {'has_precipitation': True, 'temperature': 0.95},
 'minecraft:basalt_deltas': {'has_precipitation': False, 'temperature': 2.0},
 'minecraft:beach': {'has_precipitation': True, 'temperature': 0.8},
 'minecraft:birch_forest': {'has_precipitation': True, 'temperature': 0.6},
 'minecraft:cherry_grove': {'has_precipitation': True, 'temperature': 0.5},
 'minecraft:cold_ocean': {'has_precipitation': True, 'temperature': 0.5},
 'minecraft:crimson_forest': {'has_precipitation': False, 'temperature': 2.0},
 'minecraft:dark_forest': {'has_precipitation': True, 'temperature': 0.7},
 'minecraft:deep_cold_ocean': {'has_precipitation': True, 'temperature': 0.5},
 'minecraft:deep_dark': {'has_precipitation': True, 'temperature': 0.8},
 'minecraft:deep_frozen_ocean': {'has_precipitation': True, 'temperature': 0.5},
 'minecraft:deep_lukewarm_ocean': {'has_precipitation': True, 'temperature': 0.5},
 'minecraft:deep_ocean': {'has_precipitation': True, 'temperature': 0.5},
 'minecraft:desert': {'has_precipitation': False, 'temperature': 2.0},
 'minecraft:dripstone_caves': {'has_precipitation': True, 'temperature': 0.8},
 'minecraft:end_barrens': {'has_precipitation': False, 'temperature': 0.5},
 'minecraft:end_highlands': {'has_precipitation': False, 'temperature': 0.5},
 'minecraft:end_midlands': {'has_precipitation': False, 'temperature': 0.5},
 'minecraft:eroded_badlands': {'has_precipitation': False, 'temperature': 2.0},
 'minecraft:flower_forest': {'has_precipitation': True, 'temperature': 0.7},
 'minecraft:forest': {'has_precipitation': True, 'temperature': 0.7},
 'minecraft:frozen_ocean': {'has_precipitation': True, 'temperature': 0.0},
 'minecraft:frozen_peaks': {'has_precipitation': True, 'temperature': -0.7},
 'minecraft:frozen_river': {'has_precipitation': True, 'temperature': 0.0},
 'minecraft:grove': {'has_precipitation': True, 'temperature': -0.2},
 'minecraft:ice_spikes': {'has_precipitation': True, 'temperature': 0.0},
 'minecraft:jagged_peaks': {'has_precipitation': True, 'temperature': -0.7},
 'minecraft:jungle': {'has_precipitation': True, 'temperature': 0.95},
 'minecraft:lukewarm_ocean': {'has_precipitation': True, 'temperature': 0.5},
 'minecraft:lush_caves': {'has_precipitation': True, 'temperature': 0.5},
 'minecraft:mangrove_swamp': {'has_precipitation': True, 'temperature': 0.8},
 'minecraft:meadow': {'has_precipitation': True, 'temperature': 0.5},
 'minecraft:mushroom_fields': {'has_precipitation': True, 'temperature': 0.9},
 'minecraft:nether_wastes': {'has_precipitation': False, 'temperature': 2.0},
 'minecraft:ocean': {'has_precipitation': True, 'temperature': 0.5},
 'minecraft:old_growth_birch_forest': {'has_precipitation': True, 'temperature': 0.6},
 'minecraft:old_growth_pine_taiga': {'has_precipitation': True, 'temperature': 0.3},
 'minecraft:old_growth_spruce_taiga': {'has_precipitation': True, 'temperature': 0.25},
 'minecraft:plains': {'has_precipitation': True, 'temperature': 0.8},
 'minecraft:river': {'has_precipitation': True, 'temperature': 0.5},
 'minecraft:savanna': {'has_precipitation': False, 'temperature': 2.0},
 'minecraft:savanna_plateau': {'has_precipitation': False, 'temperature': 2.0},
 'minecraft:small_end_islands': {'has_precipitation': False, 'temperature': 0.5},
 'minecraft:snowy_beach': {'has_precipitation': True, 'temperature': 0.05},
 'minecraft:snowy_plains': {'has_precipitation': True, 'temperature': 0.0},
 'minecraft:snowy_slopes': {'has_precipitation': True, 'temperature': -0.3},
 'minecraft:snowy_taiga': {'has_precipitation': True, 'temperature': -0.5},
 'minecraft:soul_sand_valley': {'has_precipitation': False, 'temperature': 2.0},
 'minecraft:sparse_jungle': {'has_precipitation': True, 'temperature': 0.95},
 'minecraft:stony_peaks': {'has_precipitation': True, 'temperature': 1.0},
 'minecraft:stony_shore': {'has_precipitation': True, 'temperature': 0.2},
 'minecraft:sunflower_plains': {'has_precipitation': True, 'temperature': 0.8},
 'minecraft:swamp': {'has_precipitation': True, 'temperature': 0.8},
 'minecraft:taiga': {'has_precipitation': True, 'temperature': 0.25},
 'minecraft:the_end': {'has_precipitation': False, 'temperature': 0.5},
 'minecraft:the_void': {'has_precipitation': False, 'temperature': 0.5},
 'minecraft:warm_ocean': {'has_precipitation': True, 'temperature': 0.5},
 'minecraft:warped_forest': {'has_precipitation': False, 'temperature': 2.0},
 'minecraft:windswept_forest': {'has_precipitation': True, 'temperature': 0.2},
 'minecraft:windswept_gravelly_hills': {'has_precipitation': True, 'temperature': 0.2},
 'minecraft:windswept_hills': {'has_precipitation': True, 'temperature': 0.2},
 'minecraft:windswept_savanna': {'has_precipitation': False, 'temperature': 2.0},
 'minecraft:wooded_badlands': {'has_precipitation': False, 'temperature': 2.0}}

# tag id -> raw values (may reference other tags with a leading #)
BIOME_TAGS: dict[str, list[str]] = {'minecraft:has_structure/ancient_city': ['minecraft:deep_dark'],
 'minecraft:has_structure/bastion_remnant': ['minecraft:crimson_forest',
                                             'minecraft:nether_wastes',
                                             'minecraft:soul_sand_valley',
                                             'minecraft:warped_forest'],
 'minecraft:has_structure/buried_treasure': ['#minecraft:is_beach'],
 'minecraft:has_structure/desert_pyramid': ['minecraft:desert'],
 'minecraft:has_structure/end_city': ['minecraft:end_highlands', 'minecraft:end_midlands'],
 'minecraft:has_structure/igloo': ['minecraft:snowy_taiga',
                                   'minecraft:snowy_plains',
                                   'minecraft:snowy_slopes'],
 'minecraft:has_structure/jungle_temple': ['minecraft:bamboo_jungle', 'minecraft:jungle'],
 'minecraft:has_structure/mineshaft': ['#minecraft:is_ocean',
                                       '#minecraft:is_river',
                                       '#minecraft:is_beach',
                                       '#minecraft:is_mountain',
                                       '#minecraft:is_hill',
                                       '#minecraft:is_taiga',
                                       '#minecraft:is_jungle',
                                       '#minecraft:is_forest',
                                       'minecraft:stony_shore',
                                       'minecraft:mushroom_fields',
                                       'minecraft:ice_spikes',
                                       'minecraft:windswept_savanna',
                                       'minecraft:desert',
                                       'minecraft:savanna',
                                       'minecraft:snowy_plains',
                                       'minecraft:plains',
                                       'minecraft:sunflower_plains',
                                       'minecraft:swamp',
                                       'minecraft:mangrove_swamp',
                                       'minecraft:savanna_plateau',
                                       'minecraft:dripstone_caves',
                                       'minecraft:lush_caves'],
 'minecraft:has_structure/mineshaft_mesa': ['#minecraft:is_badlands'],
 'minecraft:has_structure/nether_fortress': ['#minecraft:is_nether'],
 'minecraft:has_structure/nether_fossil': ['minecraft:soul_sand_valley'],
 'minecraft:has_structure/ocean_monument': ['#minecraft:is_deep_ocean'],
 'minecraft:has_structure/ocean_ruin_cold': ['minecraft:frozen_ocean',
                                             'minecraft:cold_ocean',
                                             'minecraft:ocean',
                                             'minecraft:deep_frozen_ocean',
                                             'minecraft:deep_cold_ocean',
                                             'minecraft:deep_ocean'],
 'minecraft:has_structure/ocean_ruin_warm': ['minecraft:lukewarm_ocean',
                                             'minecraft:warm_ocean',
                                             'minecraft:deep_lukewarm_ocean'],
 'minecraft:has_structure/pillager_outpost': ['minecraft:desert',
                                              'minecraft:plains',
                                              'minecraft:savanna',
                                              'minecraft:snowy_plains',
                                              'minecraft:taiga',
                                              '#minecraft:is_mountain',
                                              'minecraft:grove'],
 'minecraft:has_structure/ruined_portal_desert': ['minecraft:desert'],
 'minecraft:has_structure/ruined_portal_jungle': ['#minecraft:is_jungle'],
 'minecraft:has_structure/ruined_portal_mountain': ['#minecraft:is_badlands',
                                                    '#minecraft:is_hill',
                                                    'minecraft:savanna_plateau',
                                                    'minecraft:windswept_savanna',
                                                    'minecraft:stony_shore',
                                                    '#minecraft:is_mountain'],
 'minecraft:has_structure/ruined_portal_nether': ['#minecraft:is_nether'],
 'minecraft:has_structure/ruined_portal_ocean': ['#minecraft:is_ocean'],
 'minecraft:has_structure/ruined_portal_standard': ['#minecraft:is_beach',
                                                    '#minecraft:is_river',
                                                    '#minecraft:is_taiga',
                                                    '#minecraft:is_forest',
                                                    'minecraft:mushroom_fields',
                                                    'minecraft:ice_spikes',
                                                    'minecraft:dripstone_caves',
                                                    'minecraft:lush_caves',
                                                    'minecraft:savanna',
                                                    'minecraft:snowy_plains',
                                                    'minecraft:plains',
                                                    'minecraft:sunflower_plains'],
 'minecraft:has_structure/ruined_portal_swamp': ['minecraft:swamp', 'minecraft:mangrove_swamp'],
 'minecraft:has_structure/shipwreck': ['#minecraft:is_ocean'],
 'minecraft:has_structure/shipwreck_beached': ['#minecraft:is_beach'],
 'minecraft:has_structure/stronghold': ['#minecraft:is_overworld'],
 'minecraft:has_structure/swamp_hut': ['minecraft:swamp'],
 'minecraft:has_structure/trail_ruins': ['minecraft:taiga',
                                         'minecraft:snowy_taiga',
                                         'minecraft:old_growth_pine_taiga',
                                         'minecraft:old_growth_spruce_taiga',
                                         'minecraft:old_growth_birch_forest',
                                         'minecraft:jungle'],
 'minecraft:has_structure/trial_chambers': ['minecraft:mushroom_fields',
                                            'minecraft:deep_frozen_ocean',
                                            'minecraft:frozen_ocean',
                                            'minecraft:deep_cold_ocean',
                                            'minecraft:cold_ocean',
                                            'minecraft:deep_ocean',
                                            'minecraft:ocean',
                                            'minecraft:deep_lukewarm_ocean',
                                            'minecraft:lukewarm_ocean',
                                            'minecraft:warm_ocean',
                                            'minecraft:stony_shore',
                                            'minecraft:swamp',
                                            'minecraft:mangrove_swamp',
                                            'minecraft:snowy_slopes',
                                            'minecraft:snowy_plains',
                                            'minecraft:snowy_beach',
                                            'minecraft:windswept_gravelly_hills',
                                            'minecraft:grove',
                                            'minecraft:windswept_hills',
                                            'minecraft:snowy_taiga',
                                            'minecraft:windswept_forest',
                                            'minecraft:taiga',
                                            'minecraft:plains',
                                            'minecraft:meadow',
                                            'minecraft:beach',
                                            'minecraft:forest',
                                            'minecraft:old_growth_spruce_taiga',
                                            'minecraft:flower_forest',
                                            'minecraft:birch_forest',
                                            'minecraft:dark_forest',
                                            'minecraft:savanna_plateau',
                                            'minecraft:savanna',
                                            'minecraft:jungle',
                                            'minecraft:badlands',
                                            'minecraft:desert',
                                            'minecraft:wooded_badlands',
                                            'minecraft:jagged_peaks',
                                            'minecraft:stony_peaks',
                                            'minecraft:frozen_river',
                                            'minecraft:river',
                                            'minecraft:ice_spikes',
                                            'minecraft:old_growth_pine_taiga',
                                            'minecraft:sunflower_plains',
                                            'minecraft:old_growth_birch_forest',
                                            'minecraft:sparse_jungle',
                                            'minecraft:bamboo_jungle',
                                            'minecraft:eroded_badlands',
                                            'minecraft:windswept_savanna',
                                            'minecraft:cherry_grove',
                                            'minecraft:frozen_peaks',
                                            'minecraft:dripstone_caves',
                                            'minecraft:lush_caves'],
 'minecraft:has_structure/village_desert': ['minecraft:desert'],
 'minecraft:has_structure/village_plains': ['minecraft:plains', 'minecraft:meadow'],
 'minecraft:has_structure/village_savanna': ['minecraft:savanna'],
 'minecraft:has_structure/village_snowy': ['minecraft:snowy_plains'],
 'minecraft:has_structure/village_taiga': ['minecraft:taiga'],
 'minecraft:has_structure/woodland_mansion': ['minecraft:dark_forest'],
 'minecraft:is_badlands': ['minecraft:badlands',
                           'minecraft:eroded_badlands',
                           'minecraft:wooded_badlands'],
 'minecraft:is_beach': ['minecraft:beach', 'minecraft:snowy_beach'],
 'minecraft:is_deep_ocean': ['minecraft:deep_frozen_ocean',
                             'minecraft:deep_cold_ocean',
                             'minecraft:deep_ocean',
                             'minecraft:deep_lukewarm_ocean'],
 'minecraft:is_end': ['minecraft:the_end',
                      'minecraft:end_highlands',
                      'minecraft:end_midlands',
                      'minecraft:small_end_islands',
                      'minecraft:end_barrens'],
 'minecraft:is_forest': ['minecraft:forest',
                         'minecraft:flower_forest',
                         'minecraft:birch_forest',
                         'minecraft:old_growth_birch_forest',
                         'minecraft:dark_forest',
                         'minecraft:grove'],
 'minecraft:is_hill': ['minecraft:windswept_hills',
                       'minecraft:windswept_forest',
                       'minecraft:windswept_gravelly_hills'],
 'minecraft:is_jungle': ['minecraft:bamboo_jungle', 'minecraft:jungle', 'minecraft:sparse_jungle'],
 'minecraft:is_mountain': ['minecraft:meadow',
                           'minecraft:frozen_peaks',
                           'minecraft:jagged_peaks',
                           'minecraft:stony_peaks',
                           'minecraft:snowy_slopes',
                           'minecraft:cherry_grove'],
 'minecraft:is_nether': ['minecraft:nether_wastes',
                         'minecraft:soul_sand_valley',
                         'minecraft:crimson_forest',
                         'minecraft:warped_forest',
                         'minecraft:basalt_deltas'],
 'minecraft:is_ocean': ['#minecraft:is_deep_ocean',
                        'minecraft:frozen_ocean',
                        'minecraft:ocean',
                        'minecraft:cold_ocean',
                        'minecraft:lukewarm_ocean',
                        'minecraft:warm_ocean'],
 'minecraft:is_overworld': ['minecraft:mushroom_fields',
                            'minecraft:deep_frozen_ocean',
                            'minecraft:frozen_ocean',
                            'minecraft:deep_cold_ocean',
                            'minecraft:cold_ocean',
                            'minecraft:deep_ocean',
                            'minecraft:ocean',
                            'minecraft:deep_lukewarm_ocean',
                            'minecraft:lukewarm_ocean',
                            'minecraft:warm_ocean',
                            'minecraft:stony_shore',
                            'minecraft:swamp',
                            'minecraft:mangrove_swamp',
                            'minecraft:snowy_slopes',
                            'minecraft:snowy_plains',
                            'minecraft:snowy_beach',
                            'minecraft:windswept_gravelly_hills',
                            'minecraft:grove',
                            'minecraft:windswept_hills',
                            'minecraft:snowy_taiga',
                            'minecraft:windswept_forest',
                            'minecraft:taiga',
                            'minecraft:plains',
                            'minecraft:meadow',
                            'minecraft:beach',
                            'minecraft:forest',
                            'minecraft:old_growth_spruce_taiga',
                            'minecraft:flower_forest',
                            'minecraft:birch_forest',
                            'minecraft:dark_forest',
                            'minecraft:savanna_plateau',
                            'minecraft:savanna',
                            'minecraft:jungle',
                            'minecraft:badlands',
                            'minecraft:desert',
                            'minecraft:wooded_badlands',
                            'minecraft:jagged_peaks',
                            'minecraft:stony_peaks',
                            'minecraft:frozen_river',
                            'minecraft:river',
                            'minecraft:ice_spikes',
                            'minecraft:old_growth_pine_taiga',
                            'minecraft:sunflower_plains',
                            'minecraft:old_growth_birch_forest',
                            'minecraft:sparse_jungle',
                            'minecraft:bamboo_jungle',
                            'minecraft:eroded_badlands',
                            'minecraft:windswept_savanna',
                            'minecraft:cherry_grove',
                            'minecraft:frozen_peaks',
                            'minecraft:dripstone_caves',
                            'minecraft:lush_caves',
                            'minecraft:deep_dark'],
 'minecraft:is_river': ['minecraft:river', 'minecraft:frozen_river'],
 'minecraft:is_savanna': ['minecraft:savanna',
                          'minecraft:savanna_plateau',
                          'minecraft:windswept_savanna'],
 'minecraft:is_taiga': ['minecraft:taiga',
                        'minecraft:snowy_taiga',
                        'minecraft:old_growth_pine_taiga',
                        'minecraft:old_growth_spruce_taiga']}

# structure id -> the structure json as shipped
STRUCTURES: dict[str, dict] = {'minecraft:ancient_city': {'biomes': '#minecraft:has_structure/ancient_city',
                            'max_distance_from_center': 116,
                            'size': 7,
                            'spawn_overrides': {'ambient': {'bounding_box': 'full', 'spawns': []},
                                                'axolotls': {'bounding_box': 'full', 'spawns': []},
                                                'creature': {'bounding_box': 'full', 'spawns': []},
                                                'misc': {'bounding_box': 'full', 'spawns': []},
                                                'monster': {'bounding_box': 'full', 'spawns': []},
                                                'underground_water_creature': {'bounding_box': 'full',
                                                                               'spawns': []},
                                                'water_ambient': {'bounding_box': 'full',
                                                                  'spawns': []},
                                                'water_creature': {'bounding_box': 'full',
                                                                   'spawns': []}},
                            'start_height': {'absolute': -27},
                            'start_jigsaw_name': 'minecraft:city_anchor',
                            'start_pool': 'minecraft:ancient_city/city_center',
                            'step': 'underground_decoration',
                            'terrain_adaptation': 'beard_box',
                            'type': 'minecraft:jigsaw',
                            'use_expansion_hack': False},
 'minecraft:bastion_remnant': {'biomes': '#minecraft:has_structure/bastion_remnant',
                               'max_distance_from_center': 80,
                               'size': 6,
                               'spawn_overrides': {},
                               'start_height': {'absolute': 33},
                               'start_pool': 'minecraft:bastion/starts',
                               'step': 'surface_structures',
                               'type': 'minecraft:jigsaw',
                               'use_expansion_hack': False},
 'minecraft:buried_treasure': {'biomes': '#minecraft:has_structure/buried_treasure',
                               'spawn_overrides': {},
                               'step': 'underground_structures',
                               'type': 'minecraft:buried_treasure'},
 'minecraft:desert_pyramid': {'biomes': '#minecraft:has_structure/desert_pyramid',
                              'spawn_overrides': {},
                              'step': 'surface_structures',
                              'type': 'minecraft:desert_pyramid'},
 'minecraft:end_city': {'biomes': '#minecraft:has_structure/end_city',
                        'spawn_overrides': {},
                        'step': 'surface_structures',
                        'type': 'minecraft:end_city'},
 'minecraft:fortress': {'biomes': '#minecraft:has_structure/nether_fortress',
                        'spawn_overrides': {'monster': {'bounding_box': 'piece',
                                                        'spawns': [{'maxCount': 3,
                                                                    'minCount': 2,
                                                                    'type': 'minecraft:blaze',
                                                                    'weight': 10},
                                                                   {'maxCount': 4,
                                                                    'minCount': 4,
                                                                    'type': 'minecraft:zombified_piglin',
                                                                    'weight': 5},
                                                                   {'maxCount': 5,
                                                                    'minCount': 5,
                                                                    'type': 'minecraft:wither_skeleton',
                                                                    'weight': 8},
                                                                   {'maxCount': 5,
                                                                    'minCount': 5,
                                                                    'type': 'minecraft:skeleton',
                                                                    'weight': 2},
                                                                   {'maxCount': 4,
                                                                    'minCount': 4,
                                                                    'type': 'minecraft:magma_cube',
                                                                    'weight': 3}]}},
                        'step': 'underground_decoration',
                        'type': 'minecraft:fortress'},
 'minecraft:igloo': {'biomes': '#minecraft:has_structure/igloo',
                     'spawn_overrides': {},
                     'step': 'surface_structures',
                     'type': 'minecraft:igloo'},
 'minecraft:jungle_pyramid': {'biomes': '#minecraft:has_structure/jungle_temple',
                              'spawn_overrides': {},
                              'step': 'surface_structures',
                              'type': 'minecraft:jungle_temple'},
 'minecraft:mansion': {'biomes': '#minecraft:has_structure/woodland_mansion',
                       'spawn_overrides': {},
                       'step': 'surface_structures',
                       'type': 'minecraft:woodland_mansion'},
 'minecraft:mineshaft': {'biomes': '#minecraft:has_structure/mineshaft',
                         'mineshaft_type': 'normal',
                         'spawn_overrides': {},
                         'step': 'underground_structures',
                         'type': 'minecraft:mineshaft'},
 'minecraft:mineshaft_mesa': {'biomes': '#minecraft:has_structure/mineshaft_mesa',
                              'mineshaft_type': 'mesa',
                              'spawn_overrides': {},
                              'step': 'underground_structures',
                              'type': 'minecraft:mineshaft'},
 'minecraft:monument': {'biomes': '#minecraft:has_structure/ocean_monument',
                        'spawn_overrides': {'axolotls': {'bounding_box': 'full', 'spawns': []},
                                            'monster': {'bounding_box': 'full',
                                                        'spawns': [{'maxCount': 4,
                                                                    'minCount': 2,
                                                                    'type': 'minecraft:guardian',
                                                                    'weight': 1}]},
                                            'underground_water_creature': {'bounding_box': 'full',
                                                                           'spawns': []}},
                        'step': 'surface_structures',
                        'type': 'minecraft:ocean_monument'},
 'minecraft:nether_fossil': {'biomes': '#minecraft:has_structure/nether_fossil',
                             'height': {'max_inclusive': {'below_top': 2},
                                        'min_inclusive': {'absolute': 32},
                                        'type': 'minecraft:uniform'},
                             'spawn_overrides': {},
                             'step': 'underground_decoration',
                             'terrain_adaptation': 'beard_thin',
                             'type': 'minecraft:nether_fossil'},
 'minecraft:ocean_ruin_cold': {'biome_temp': 'cold',
                               'biomes': '#minecraft:has_structure/ocean_ruin_cold',
                               'cluster_probability': 0.9,
                               'large_probability': 0.3,
                               'spawn_overrides': {},
                               'step': 'surface_structures',
                               'type': 'minecraft:ocean_ruin'},
 'minecraft:ocean_ruin_warm': {'biome_temp': 'warm',
                               'biomes': '#minecraft:has_structure/ocean_ruin_warm',
                               'cluster_probability': 0.9,
                               'large_probability': 0.3,
                               'spawn_overrides': {},
                               'step': 'surface_structures',
                               'type': 'minecraft:ocean_ruin'},
 'minecraft:pillager_outpost': {'biomes': '#minecraft:has_structure/pillager_outpost',
                                'max_distance_from_center': 80,
                                'project_start_to_heightmap': 'WORLD_SURFACE_WG',
                                'size': 7,
                                'spawn_overrides': {'monster': {'bounding_box': 'full',
                                                                'spawns': [{'maxCount': 1,
                                                                            'minCount': 1,
                                                                            'type': 'minecraft:pillager',
                                                                            'weight': 1}]}},
                                'start_height': {'absolute': 0},
                                'start_pool': 'minecraft:pillager_outpost/base_plates',
                                'step': 'surface_structures',
                                'terrain_adaptation': 'beard_thin',
                                'type': 'minecraft:jigsaw',
                                'use_expansion_hack': True},
 'minecraft:ruined_portal': {'biomes': '#minecraft:has_structure/ruined_portal_standard',
                             'setups': [{'air_pocket_probability': 1.0,
                                         'can_be_cold': True,
                                         'mossiness': 0.2,
                                         'overgrown': False,
                                         'placement': 'underground',
                                         'replace_with_blackstone': False,
                                         'vines': False,
                                         'weight': 0.5},
                                        {'air_pocket_probability': 0.5,
                                         'can_be_cold': True,
                                         'mossiness': 0.2,
                                         'overgrown': False,
                                         'placement': 'on_land_surface',
                                         'replace_with_blackstone': False,
                                         'vines': False,
                                         'weight': 0.5}],
                             'spawn_overrides': {},
                             'step': 'surface_structures',
                             'type': 'minecraft:ruined_portal'},
 'minecraft:ruined_portal_desert': {'biomes': '#minecraft:has_structure/ruined_portal_desert',
                                    'setups': [{'air_pocket_probability': 0.0,
                                                'can_be_cold': False,
                                                'mossiness': 0.0,
                                                'overgrown': False,
                                                'placement': 'partly_buried',
                                                'replace_with_blackstone': False,
                                                'vines': False,
                                                'weight': 1.0}],
                                    'spawn_overrides': {},
                                    'step': 'surface_structures',
                                    'type': 'minecraft:ruined_portal'},
 'minecraft:ruined_portal_jungle': {'biomes': '#minecraft:has_structure/ruined_portal_jungle',
                                    'setups': [{'air_pocket_probability': 0.5,
                                                'can_be_cold': False,
                                                'mossiness': 0.8,
                                                'overgrown': True,
                                                'placement': 'on_land_surface',
                                                'replace_with_blackstone': False,
                                                'vines': True,
                                                'weight': 1.0}],
                                    'spawn_overrides': {},
                                    'step': 'surface_structures',
                                    'type': 'minecraft:ruined_portal'},
 'minecraft:ruined_portal_mountain': {'biomes': '#minecraft:has_structure/ruined_portal_mountain',
                                      'setups': [{'air_pocket_probability': 1.0,
                                                  'can_be_cold': True,
                                                  'mossiness': 0.2,
                                                  'overgrown': False,
                                                  'placement': 'in_mountain',
                                                  'replace_with_blackstone': False,
                                                  'vines': False,
                                                  'weight': 0.5},
                                                 {'air_pocket_probability': 0.5,
                                                  'can_be_cold': True,
                                                  'mossiness': 0.2,
                                                  'overgrown': False,
                                                  'placement': 'on_land_surface',
                                                  'replace_with_blackstone': False,
                                                  'vines': False,
                                                  'weight': 0.5}],
                                      'spawn_overrides': {},
                                      'step': 'surface_structures',
                                      'type': 'minecraft:ruined_portal'},
 'minecraft:ruined_portal_nether': {'biomes': '#minecraft:has_structure/ruined_portal_nether',
                                    'setups': [{'air_pocket_probability': 0.5,
                                                'can_be_cold': False,
                                                'mossiness': 0.0,
                                                'overgrown': False,
                                                'placement': 'in_nether',
                                                'replace_with_blackstone': True,
                                                'vines': False,
                                                'weight': 1.0}],
                                    'spawn_overrides': {},
                                    'step': 'surface_structures',
                                    'type': 'minecraft:ruined_portal'},
 'minecraft:ruined_portal_ocean': {'biomes': '#minecraft:has_structure/ruined_portal_ocean',
                                   'setups': [{'air_pocket_probability': 0.0,
                                               'can_be_cold': True,
                                               'mossiness': 0.8,
                                               'overgrown': False,
                                               'placement': 'on_ocean_floor',
                                               'replace_with_blackstone': False,
                                               'vines': False,
                                               'weight': 1.0}],
                                   'spawn_overrides': {},
                                   'step': 'surface_structures',
                                   'type': 'minecraft:ruined_portal'},
 'minecraft:ruined_portal_swamp': {'biomes': '#minecraft:has_structure/ruined_portal_swamp',
                                   'setups': [{'air_pocket_probability': 0.0,
                                               'can_be_cold': False,
                                               'mossiness': 0.5,
                                               'overgrown': False,
                                               'placement': 'on_ocean_floor',
                                               'replace_with_blackstone': False,
                                               'vines': True,
                                               'weight': 1.0}],
                                   'spawn_overrides': {},
                                   'step': 'surface_structures',
                                   'type': 'minecraft:ruined_portal'},
 'minecraft:shipwreck': {'biomes': '#minecraft:has_structure/shipwreck',
                         'is_beached': False,
                         'spawn_overrides': {},
                         'step': 'surface_structures',
                         'type': 'minecraft:shipwreck'},
 'minecraft:shipwreck_beached': {'biomes': '#minecraft:has_structure/shipwreck_beached',
                                 'is_beached': True,
                                 'spawn_overrides': {},
                                 'step': 'surface_structures',
                                 'type': 'minecraft:shipwreck'},
 'minecraft:stronghold': {'biomes': '#minecraft:has_structure/stronghold',
                          'spawn_overrides': {},
                          'step': 'surface_structures',
                          'terrain_adaptation': 'bury',
                          'type': 'minecraft:stronghold'},
 'minecraft:swamp_hut': {'biomes': '#minecraft:has_structure/swamp_hut',
                         'spawn_overrides': {'creature': {'bounding_box': 'piece',
                                                          'spawns': [{'maxCount': 1,
                                                                      'minCount': 1,
                                                                      'type': 'minecraft:cat',
                                                                      'weight': 1}]},
                                             'monster': {'bounding_box': 'piece',
                                                         'spawns': [{'maxCount': 1,
                                                                     'minCount': 1,
                                                                     'type': 'minecraft:witch',
                                                                     'weight': 1}]}},
                         'step': 'surface_structures',
                         'type': 'minecraft:swamp_hut'},
 'minecraft:trail_ruins': {'biomes': '#minecraft:has_structure/trail_ruins',
                           'max_distance_from_center': 80,
                           'project_start_to_heightmap': 'WORLD_SURFACE_WG',
                           'size': 7,
                           'spawn_overrides': {},
                           'start_height': {'absolute': -15},
                           'start_pool': 'minecraft:trail_ruins/tower',
                           'step': 'underground_structures',
                           'terrain_adaptation': 'bury',
                           'type': 'minecraft:jigsaw',
                           'use_expansion_hack': False},
 'minecraft:trial_chambers': {'biomes': '#minecraft:has_structure/trial_chambers',
                              'dimension_padding': 10,
                              'liquid_settings': 'ignore_waterlogging',
                              'max_distance_from_center': 116,
                              'pool_aliases': [{'groups': [{'data': [{'alias': 'minecraft:trial_chambers/spawner/contents/ranged',
                                                                      'target': 'minecraft:trial_chambers/spawner/ranged/skeleton',
                                                                      'type': 'minecraft:direct'},
                                                                     {'alias': 'minecraft:trial_chambers/spawner/contents/slow_ranged',
                                                                      'target': 'minecraft:trial_chambers/spawner/slow_ranged/skeleton',
                                                                      'type': 'minecraft:direct'}],
                                                            'weight': 1},
                                                           {'data': [{'alias': 'minecraft:trial_chambers/spawner/contents/ranged',
                                                                      'target': 'minecraft:trial_chambers/spawner/ranged/stray',
                                                                      'type': 'minecraft:direct'},
                                                                     {'alias': 'minecraft:trial_chambers/spawner/contents/slow_ranged',
                                                                      'target': 'minecraft:trial_chambers/spawner/slow_ranged/stray',
                                                                      'type': 'minecraft:direct'}],
                                                            'weight': 1},
                                                           {'data': [{'alias': 'minecraft:trial_chambers/spawner/contents/ranged',
                                                                      'target': 'minecraft:trial_chambers/spawner/ranged/poison_skeleton',
                                                                      'type': 'minecraft:direct'},
                                                                     {'alias': 'minecraft:trial_chambers/spawner/contents/slow_ranged',
                                                                      'target': 'minecraft:trial_chambers/spawner/slow_ranged/poison_skeleton',
                                                                      'type': 'minecraft:direct'}],
                                                            'weight': 1}],
                                                'type': 'minecraft:random_group'},
                                               {'alias': 'minecraft:trial_chambers/spawner/contents/melee',
                                                'targets': [{'data': 'minecraft:trial_chambers/spawner/melee/zombie',
                                                             'weight': 1},
                                                            {'data': 'minecraft:trial_chambers/spawner/melee/husk',
                                                             'weight': 1},
                                                            {'data': 'minecraft:trial_chambers/spawner/melee/spider',
                                                             'weight': 1}],
                                                'type': 'minecraft:random'},
                                               {'alias': 'minecraft:trial_chambers/spawner/contents/small_melee',
                                                'targets': [{'data': 'minecraft:trial_chambers/spawner/small_melee/slime',
                                                             'weight': 1},
                                                            {'data': 'minecraft:trial_chambers/spawner/small_melee/cave_spider',
                                                             'weight': 1},
                                                            {'data': 'minecraft:trial_chambers/spawner/small_melee/silverfish',
                                                             'weight': 1},
                                                            {'data': 'minecraft:trial_chambers/spawner/small_melee/baby_zombie',
                                                             'weight': 1}],
                                                'type': 'minecraft:random'}],
                              'size': 20,
                              'spawn_overrides': {'ambient': {'bounding_box': 'piece',
                                                              'spawns': []},
                                                  'axolotls': {'bounding_box': 'piece',
                                                               'spawns': []},
                                                  'creature': {'bounding_box': 'piece',
                                                               'spawns': []},
                                                  'misc': {'bounding_box': 'piece', 'spawns': []},
                                                  'monster': {'bounding_box': 'piece',
                                                              'spawns': []},
                                                  'underground_water_creature': {'bounding_box': 'piece',
                                                                                 'spawns': []},
                                                  'water_ambient': {'bounding_box': 'piece',
                                                                    'spawns': []},
                                                  'water_creature': {'bounding_box': 'piece',
                                                                     'spawns': []}},
                              'start_height': {'max_inclusive': {'absolute': -20},
                                               'min_inclusive': {'absolute': -40},
                                               'type': 'minecraft:uniform'},
                              'start_pool': 'minecraft:trial_chambers/chamber/end',
                              'step': 'underground_structures',
                              'terrain_adaptation': 'encapsulate',
                              'type': 'minecraft:jigsaw',
                              'use_expansion_hack': False},
 'minecraft:village_desert': {'biomes': '#minecraft:has_structure/village_desert',
                              'max_distance_from_center': 80,
                              'project_start_to_heightmap': 'WORLD_SURFACE_WG',
                              'size': 6,
                              'spawn_overrides': {},
                              'start_height': {'absolute': 0},
                              'start_pool': 'minecraft:village/desert/town_centers',
                              'step': 'surface_structures',
                              'terrain_adaptation': 'beard_thin',
                              'type': 'minecraft:jigsaw',
                              'use_expansion_hack': True},
 'minecraft:village_plains': {'biomes': '#minecraft:has_structure/village_plains',
                              'max_distance_from_center': 80,
                              'project_start_to_heightmap': 'WORLD_SURFACE_WG',
                              'size': 6,
                              'spawn_overrides': {},
                              'start_height': {'absolute': 0},
                              'start_pool': 'minecraft:village/plains/town_centers',
                              'step': 'surface_structures',
                              'terrain_adaptation': 'beard_thin',
                              'type': 'minecraft:jigsaw',
                              'use_expansion_hack': True},
 'minecraft:village_savanna': {'biomes': '#minecraft:has_structure/village_savanna',
                               'max_distance_from_center': 80,
                               'project_start_to_heightmap': 'WORLD_SURFACE_WG',
                               'size': 6,
                               'spawn_overrides': {},
                               'start_height': {'absolute': 0},
                               'start_pool': 'minecraft:village/savanna/town_centers',
                               'step': 'surface_structures',
                               'terrain_adaptation': 'beard_thin',
                               'type': 'minecraft:jigsaw',
                               'use_expansion_hack': True},
 'minecraft:village_snowy': {'biomes': '#minecraft:has_structure/village_snowy',
                             'max_distance_from_center': 80,
                             'project_start_to_heightmap': 'WORLD_SURFACE_WG',
                             'size': 6,
                             'spawn_overrides': {},
                             'start_height': {'absolute': 0},
                             'start_pool': 'minecraft:village/snowy/town_centers',
                             'step': 'surface_structures',
                             'terrain_adaptation': 'beard_thin',
                             'type': 'minecraft:jigsaw',
                             'use_expansion_hack': True},
 'minecraft:village_taiga': {'biomes': '#minecraft:has_structure/village_taiga',
                             'max_distance_from_center': 80,
                             'project_start_to_heightmap': 'WORLD_SURFACE_WG',
                             'size': 6,
                             'spawn_overrides': {},
                             'start_height': {'absolute': 0},
                             'start_pool': 'minecraft:village/taiga/town_centers',
                             'step': 'surface_structures',
                             'terrain_adaptation': 'beard_thin',
                             'type': 'minecraft:jigsaw',
                             'use_expansion_hack': True}}

# structure_set id -> placement summary and weighted member structures
STRUCTURE_SETS: dict[str, dict] = {'minecraft:ancient_cities': {'frequency': None,
                              'separation': 8,
                              'spacing': 24,
                              'structures': [['minecraft:ancient_city', 1]],
                              'type': 'minecraft:random_spread'},
 'minecraft:buried_treasures': {'frequency': 0.01,
                                'separation': 0,
                                'spacing': 1,
                                'structures': [['minecraft:buried_treasure', 1]],
                                'type': 'minecraft:random_spread'},
 'minecraft:desert_pyramids': {'frequency': None,
                               'separation': 8,
                               'spacing': 32,
                               'structures': [['minecraft:desert_pyramid', 1]],
                               'type': 'minecraft:random_spread'},
 'minecraft:end_cities': {'frequency': None,
                          'separation': 11,
                          'spacing': 20,
                          'structures': [['minecraft:end_city', 1]],
                          'type': 'minecraft:random_spread'},
 'minecraft:igloos': {'frequency': None,
                      'separation': 8,
                      'spacing': 32,
                      'structures': [['minecraft:igloo', 1]],
                      'type': 'minecraft:random_spread'},
 'minecraft:jungle_temples': {'frequency': None,
                              'separation': 8,
                              'spacing': 32,
                              'structures': [['minecraft:jungle_pyramid', 1]],
                              'type': 'minecraft:random_spread'},
 'minecraft:mineshafts': {'frequency': 0.004,
                          'separation': 0,
                          'spacing': 1,
                          'structures': [['minecraft:mineshaft', 1],
                                         ['minecraft:mineshaft_mesa', 1]],
                          'type': 'minecraft:random_spread'},
 'minecraft:nether_complexes': {'frequency': None,
                                'separation': 4,
                                'spacing': 27,
                                'structures': [['minecraft:fortress', 2],
                                               ['minecraft:bastion_remnant', 3]],
                                'type': 'minecraft:random_spread'},
 'minecraft:nether_fossils': {'frequency': None,
                              'separation': 1,
                              'spacing': 2,
                              'structures': [['minecraft:nether_fossil', 1]],
                              'type': 'minecraft:random_spread'},
 'minecraft:ocean_monuments': {'frequency': None,
                               'separation': 5,
                               'spacing': 32,
                               'structures': [['minecraft:monument', 1]],
                               'type': 'minecraft:random_spread'},
 'minecraft:ocean_ruins': {'frequency': None,
                           'separation': 8,
                           'spacing': 20,
                           'structures': [['minecraft:ocean_ruin_cold', 1],
                                          ['minecraft:ocean_ruin_warm', 1]],
                           'type': 'minecraft:random_spread'},
 'minecraft:pillager_outposts': {'frequency': 0.2,
                                 'separation': 8,
                                 'spacing': 32,
                                 'structures': [['minecraft:pillager_outpost', 1]],
                                 'type': 'minecraft:random_spread'},
 'minecraft:ruined_portals': {'frequency': None,
                              'separation': 15,
                              'spacing': 40,
                              'structures': [['minecraft:ruined_portal', 1],
                                             ['minecraft:ruined_portal_desert', 1],
                                             ['minecraft:ruined_portal_jungle', 1],
                                             ['minecraft:ruined_portal_swamp', 1],
                                             ['minecraft:ruined_portal_mountain', 1],
                                             ['minecraft:ruined_portal_ocean', 1],
                                             ['minecraft:ruined_portal_nether', 1]],
                              'type': 'minecraft:random_spread'},
 'minecraft:shipwrecks': {'frequency': None,
                          'separation': 4,
                          'spacing': 24,
                          'structures': [['minecraft:shipwreck', 1],
                                         ['minecraft:shipwreck_beached', 1]],
                          'type': 'minecraft:random_spread'},
 'minecraft:strongholds': {'frequency': None,
                           'separation': None,
                           'spacing': None,
                           'structures': [['minecraft:stronghold', 1]],
                           'type': 'minecraft:concentric_rings'},
 'minecraft:swamp_huts': {'frequency': None,
                          'separation': 8,
                          'spacing': 32,
                          'structures': [['minecraft:swamp_hut', 1]],
                          'type': 'minecraft:random_spread'},
 'minecraft:trail_ruins': {'frequency': None,
                           'separation': 8,
                           'spacing': 34,
                           'structures': [['minecraft:trail_ruins', 1]],
                           'type': 'minecraft:random_spread'},
 'minecraft:trial_chambers': {'frequency': None,
                              'separation': 12,
                              'spacing': 34,
                              'structures': [['minecraft:trial_chambers', 1]],
                              'type': 'minecraft:random_spread'},
 'minecraft:villages': {'frequency': None,
                        'separation': 8,
                        'spacing': 34,
                        'structures': [['minecraft:village_plains', 1],
                                       ['minecraft:village_desert', 1],
                                       ['minecraft:village_savanna', 1],
                                       ['minecraft:village_snowy', 1],
                                       ['minecraft:village_taiga', 1]],
                        'type': 'minecraft:random_spread'},
 'minecraft:woodland_mansions': {'frequency': None,
                                 'separation': 20,
                                 'spacing': 80,
                                 'structures': [['minecraft:mansion', 1]],
                                 'type': 'minecraft:random_spread'}}

# sets whose members only generate in the nether or the end
NON_OVERWORLD_SETS = frozenset({"minecraft:end_cities", "minecraft:nether_complexes", "minecraft:nether_fossils"})


def overworld_biome_ids() -> list[str]:
    """Ids in #minecraft:is_overworld, in the order the tag lists them."""
    return [b for b in BIOME_TAGS["minecraft:is_overworld"] if not b.startswith("#")]
