"""Drive a headless WorldPainter (wpscript) to export the world.

WorldPainter is an external install. We locate its script runner, make sure the JVM
heap is large enough for the raster, render the export template with MM_* env vars
and stream its stdout into the reporter.
"""
from __future__ import annotations

import os
import shutil
import subprocess
import sys
from pathlib import Path

from ..paths import resource_dir, settings_path
from ..progress import Reporter
from ..project import Project

OVERWRITE_MARKER = ".overwrite_ok"


def _candidates() -> list[Path]:
    home = Path.home()
    c = [
        home / "tools" / "WorldPainter" / "WorldPainter" / "wpscript.exe",
        home / "tools" / "WorldPainter" / "wpscript.exe",
        Path(os.environ.get("ProgramFiles", r"C:\Program Files")) / "WorldPainter" / "wpscript.exe",
        Path(os.environ.get("LOCALAPPDATA", str(home / "AppData" / "Local"))) / "Programs" / "WorldPainter" / "wpscript.exe",
        home / "Applications" / "WorldPainter.app" / "Contents" / "MacOS" / "wpscript",
        Path("/Applications/WorldPainter.app/Contents/MacOS/wpscript"),
        Path("/opt/worldpainter/wpscript"),
        Path("/usr/local/bin/wpscript"),
    ]
    return c


def find_wpscript(explicit: str = "") -> str | None:
    if explicit:
        p = Path(explicit)
        if p.is_file():
            return str(p)
        if p.is_dir():
            for name in ("wpscript.exe", "wpscript"):
                if (p / name).is_file():
                    return str(p / name)
        return None
    w = shutil.which("wpscript")
    if w:
        return w
    try:
        import json
        sp = settings_path()
        if sp.exists():
            saved = json.loads(sp.read_text(encoding="utf-8")).get("wpscript_path", "")
            if saved and Path(saved).is_file():
                return saved
    except Exception:
        pass
    for c in _candidates():
        if c.is_file():
            return str(c)
    return None


def ensure_vmoptions(wpscript: str, xmx_gb: int) -> None:
    """Set the heap in wpscript.vmoptions beside the runner; keep every other line."""
    exe = Path(wpscript)
    vm = exe.with_name(exe.stem + ".vmoptions")
    lines: list[str] = []
    if vm.exists():
        lines = [ln.rstrip("\n") for ln in vm.read_text(encoding="utf-8", errors="replace").splitlines()]
    lines = [ln for ln in lines if not ln.strip().startswith("-Xmx")]
    lines.append(f"-Xmx{int(xmx_gb)}g")
    vm.write_text("\n".join(lines) + "\n", encoding="utf-8")


def template_path() -> Path:
    return resource_dir() / "pipeline" / "templates" / "export.js"


def render_script(project: Project) -> str:
    """The template reads everything from env vars; rendering only stamps a header."""
    body = template_path().read_text(encoding="utf-8")
    header = (f"// generated by MineMap for project '{project.name}'\n"
              f"// world '{project.world.name}' -> {project.world_output_dir()}\n"
              "// inputs: MM_HEIGHTMAP MM_BIOMES MM_PALETTE MM_SAVES MM_WORLD MM_SHIFTX MM_SHIFTY "
              "MM_WATER MM_LOW MM_HIGH MM_FORMAT MM_CAVES_LEVEL MM_CAVE_MIN MM_CAVE_MAX "
              "MM_CAVE_WATER MM_CAVE_SURFACE\n")
    return header + body


def build_env(project: Project) -> dict[str, str]:
    g = project.grid()
    s = project.scale
    c = project.caves
    env = dict(os.environ)
    env.update({
        "MM_HEIGHTMAP": str(project.heightmap_png).replace("\\", "/"),
        "MM_BIOMES": str(project.biomes_png).replace("\\", "/"),
        "MM_PALETTE": str(project.biomes_palette_json).replace("\\", "/"),
        "MM_SAVES": str(project.world_output_dir()).replace("\\", "/"),
        "MM_WORLD": project.world.name,
        "MM_SHIFTX": str(g.shift_x),
        "MM_SHIFTY": str(g.shift_z),
        "MM_WATER": str(s.water_level),
        "MM_LOW": str(s.build_low),
        "MM_HIGH": str(s.build_high),
        "MM_FORMAT": project.world.map_format,
        "MM_CAVES_LEVEL": str(c.level),
        "MM_CAVE_MIN": str(c.min_y),
        "MM_CAVE_MAX": str(c.max_y),
        "MM_CAVE_WATER": str(c.water_y),
        "MM_CAVE_SURFACE": "1" if c.surface_breaking else "0",
    })
    return env


def run(project: Project, reporter: Reporter) -> None:
    reporter.set_step("export")
    wps = find_wpscript(project.tools.wpscript_path)
    if not wps:
        raise RuntimeError("WorldPainter's wpscript was not found; install WorldPainter or set its path in the world tab")
    for f in (project.heightmap_png, project.biomes_png, project.biomes_palette_json):
        if not f.exists():
            raise RuntimeError(f"missing input {f.name}; run the earlier steps first")
    ensure_vmoptions(wps, project.tools.java_xmx_gb)

    out_dir = project.world_output_dir()
    out_dir.mkdir(parents=True, exist_ok=True)
    world_dir = project.world_dir()
    marker = project.out_dir / OVERWRITE_MARKER
    if world_dir.exists():
        if marker.exists():
            reporter.log(f"removing existing world {world_dir}")
            shutil.rmtree(world_dir)
        else:
            raise RuntimeError(f"world folder already exists: {world_dir}. Confirm overwrite in the build tab or pick another name")
    if marker.exists():
        marker.unlink()

    script = project.out_dir / "export.js"
    script.write_text(render_script(project), encoding="utf-8")
    env = build_env(project)
    reporter.log(f"wpscript: {wps}")
    reporter.log(f"heap: {project.tools.java_xmx_gb} GB, shift {env['MM_SHIFTX']},{env['MM_SHIFTY']}")

    creation = subprocess.CREATE_NO_WINDOW if sys.platform == "win32" else 0
    proc = subprocess.Popen([wps, str(script)], env=env, stdout=subprocess.PIPE,
                            stderr=subprocess.STDOUT, text=True, errors="replace",
                            cwd=str(project.out_dir), creationflags=creation)
    assert proc.stdout is not None
    try:
        for line in proc.stdout:
            line = line.rstrip()
            if line:
                reporter.log(line)
            if reporter.cancelled:
                proc.kill()
                reporter.check_cancel()
    finally:
        proc.stdout.close()
    rc = proc.wait()
    if rc != 0:
        raise RuntimeError(f"wpscript exited with code {rc}")
    if not (world_dir / "level.dat").exists():
        raise RuntimeError(f"export finished but {world_dir / 'level.dat'} is missing")
    reporter.log(f"exported {world_dir}")
    reporter.progress(1.0)
